##### **Performing EDA And Solving Some Questions Using Python , Pandas And Numpy**

In [1]:
# Import Required Libraries

import pandas as pd
import numpy as np

**Read csv File**

In [2]:
# Load The Cleaned Dataset 

data = pd.read_csv(r'updated_anime_dataset.csv')

**Top 5 Highest Rated Anime**

In [3]:
# nlargest(5, 'Score') Sorts The DataFrame By The 'Score' Column And Returns The 5 Rows With The Highest Values

data.nlargest(5, 'Score')

,Rank,Title,Score,Episodes,Timespan,Members
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,3218472
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2473707
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,474138
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,605113
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2146679

**Top 5 Most Popular Anime**

In [4]:
# Sort DataFrame By 'Members' In Descending Order , Then Take The First 5 Rows , head() Gives 5 Rows By Default

data.sort_values('Members',ascending=False).head()

,Rank,Title,Score,Episodes,Timespan,Members
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,3218472
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,2701154
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,2635814
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2473707
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,2228957

**Lowest Member Count**

In [5]:
# Find The Minimum Value In The 'Members' Column , Then Filter The DataFrame To The Row Matching That Minimum
# Keeping Only The 'Title' And 'Members' Columns

data[data['Members'] == data['Members'].min()][['Title','Members']]

                                                Title  Members
28  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...    27063

**Score Metrices**

In [6]:
# Compute Mean, Median, Standard Deviation, Min, And Max Of 'Score'
# Either Use The Following 5 

print(np.mean(data['Score']))
print(np.median(data['Score']))
print(np.std(data['Score']))
print(data['Score'].min())
print(data['Score'].max())

8.883199999999999
8.855
0.11604206133984339
8.71
9.1

In [7]:
# Or Just Use This One 
# Describe() Gives Count, Mean, Std, Min, Quartiles, And Max

data['Score'].describe()

count    50.00000
mean      8.88320
std       0.11722
min       8.71000
25%       8.79000
50%       8.85500
75%       8.99000
max       9.10000
Name: Score, dtype: float64

**High-Score & High-Popularity**

In [8]:
# Return Anime Title, Score, And Members Where Score >= 9.00 And Members > 1 Million
# The '&' Combines Both Boolean Conditions (Row Must Satisfy Both)

data[(data['Score'] >= 9.00) & (data['Members'] > 1000000) ][['Title','Score','Members']]

                                               Title  Score  Members
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10  3218472
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07  2473707
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05  2146679
7  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04  2701154

**Count Long-Running Anime**

In [9]:
# Animes Where Episodes > 100 Filter Rows Where 'Episodes' Exceeds 100
# Then Count How Many Titles Satisfy That Condition

print(data[data['Episodes'] > 100]['Title'].count())

3

**What Are Long-Running Anime**

In [10]:
# Same Filter As Q6
# But This Time Display The Full Rows Instead Of Just A Count

data[data['Episodes'] > 100]

,Rank,Title,Score,Episodes,Timespan,Members
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,2701154
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,309193
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,1034418

**Short-Series High Performers**

In [11]:
# List Anime With 13 Or Fewer Episodes But A Score Of 9.00 Or Higher
# Combines Two Conditions With '&' To Find Short But Highly-Rated Anime

data[ (data['Episodes'] <= 13) & (data['Score'] >= 9.00) ]

,Rank,Title,Score,Episodes,Timespan,Members
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,474138
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2146679
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,137208
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,851445
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,313446
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,472340

**Episode Count Using Custom Grouping**

In [12]:
# Define Bin Edges And Matching Labels To Group Anime By Episode Count

bins = [0, 1, 13, 26, float('inf')]

labels = ['1 Episode', '2-13 Episodes', '14-26 Episodes', '27+ Episodes']

In [13]:
# Create A New 'Episode_Bin' Column By Cutting The 'Episodes' Column Into The Ranges Defined Above Using Pd.cut()
# Include_lowest=True Ensures The Very First Value (0) Is Included In A Bin

data['Episode_Bin'] = pd.cut(
    data['Episodes'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [14]:
# Count How Many Anime Fall Into Each Episode_Bin Category, Sorted From Smallest To Largest Count

data['Episode_Bin'].value_counts().sort_values()

Episode_Bin
27+ Episodes       8
1 Episode          9
14-26 Episodes    13
2-13 Episodes     20
Name: count, dtype: int64

**Average Score by Episode Bin**

In [ ]:
# Group The Data By The 'Episode_Bin' Category, Compute The Mean 'Score' Within Each Group, And Sort Groups From Highest To Lowest Average

data.groupby('Episode_Bin')['Score'].mean().sort_values(ascending=False)

Episode_Bin
14-26 Episodes    8.844615
1 Episode         8.873333
2-13 Episodes     8.874500
27+ Episodes      8.978750
Name: Score, dtype: float64